### PR TITLE
Fix dependency sample for groovy

### PR DESCRIPTION
**Pull request by VictorDenisov**

### CODE REVIEW

**Comment by VictorDenisov** [comment]
BTW. It doesn't work with jackson 2.8. Can we do something about it? Sending it here because there is no issue tracker for this project.

**Comment by VictorDenisov** [comment]
@jasonchaffee ^^^

**Comment by jasonchaffee** [comment]
Just saw this.  I didn’t get the email notifications previously.  Is it no longer valid?

**Comment by VictorDenisov** [comment]
It is valid. I closed it because of inactivity.

**Comment by jasonchaffee** [comment]
For some reason I never got a notification until it was closed.  I will take a look in the next couple of days and look at cutting a new release.

**Comment by VictorDenisov** [comment]
It's not particularly critical. It's only about the readme file.

**Comment by VictorDenisov** [comment]
@jasonchaffee ^

**Pull request closed without merging**
